#+TITLE: Reelección consecutiva en México
#+AUTHOR: Eric Magar
#+DATE:  <2017-06-24 Sat>
#+OPTIONS: toc:nil # don't place toc in default location
#+LANGUAGE: es

#+BEGIN_CENTER
coordinado por

*Eric Magar*
#+END_CENTER

# #instrucciones y tutorial para org -> html
# #http://orgmode.org/worg/org-tutorials/org-publish-html-tutorial.html
# 
# #publish all with single command: M-x org-publish-project RET org RET

# # ##############################
# # C-c C-e # to add this template
# # ##############################
# #+OPTIONS: html-link-use-abs-url:nil html-postamble:auto
# #+OPTIONS: html-preamble:t html-scripts:t html-style:t
# #+OPTIONS: html5-fancy:nil tex:t
# #+HTML_DOCTYPE: xhtml-strict
# #+HTML_CONTAINER: div
# #+DESCRIPTION:
# #+KEYWORDS:
# #+HTML_LINK_HOME:
# #+HTML_LINK_UP:
# #+HTML_MATHJAX:
# #+HTML_HEAD:
# #+HTML_HEAD_EXTRA:
# #+SUBTITLE:
# #+INFOJS_OPT:
# #+CREATOR: <a href="http://www.gnu.org/software/emacs/">Emacs</a> 24.5.1 (<a href="http://orgmode.org">Org</a> mode 9.0.2)
# #+LATEX_HEADER:

# style sheet
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/stylesheet.css" />

#+NAME: top_tab
|---------------+------------------|
| [[file:./sitemap.org][Mapa de sitio]] | [[http://ericmagar.com][Página principal]] |
|---------------+------------------|


* Presentación
La reforma electoral de 2014 eliminó la prohibición de reelección legislativa consecutiva en vigor desde 1933. Abrió también la posibilidad de reelegir consecutivamente a los alcaldes, síndicos y regidores de los ayuntamientos. 

Las modificaciones a la constitución de los Estados Unidos Mexicanos adoptadas otorgaron discreción a los estados para definir sus propias instituciones de reelección consecutiva, pero también establecieron dos restricciones generales. Una es la duración en el cargo, de máximo doce años consecutivos para legisladores y seis para gobernantes municipales. Otra (con algunos matices) es que la postulación sólo podrá hacerla el mismo partido que eligió al representante. 

Este sitio está dedicado a reseñar la entrada en vigor de la reelección consecutiva en México. 

---------------------------------------

# /The 2014 electoral reform removed the ban for consecutive legislative reelection, in force since 1933 in Mexico. It also opened the possibility to reelect mayors and municipal councilors./ 

# /Reformers of the Mexican constitution left discretion to states in the definition of their reelection institutions, while also establishing general constraints. One is the length in office, of maximum twelve years for legislators and six for elected municipal officers. The other (with nuances) is that incumbents must be renominated by the same party that elected them./

# /This site reports on the adoption of consecutive reelection in Mexico./

# --------------------------------------
* Textos y materiales originales

- [[./textos/nayarit.org][La reelección en Nayarit]], por Sofía De la Mora Tostado (24/6/2017)
# #+ATTR_HTML: style="float:right;"
# #+ATTR_HTML: :width 15%
# [[./textos/instituciones.org][file:img/gooReel.png]]
- [[./textos/resenhaCoahuila.org][Primeras campañas reeleccionistas]], por Eric Magar (23/6/2017)
# #+ATTR_HTML: style="float:right;"
# #+ATTR_HTML: :width 15%
# [[./textos/resenhaCoahuila.org][file:img/lilyGtz.png]]
- [[./textos/clasicos.org][Clásicos sobre la reelección consecutiva]] (29/5/2017)
# #+ATTR_HTML: style="float:right;"
# #+ATTR_HTML: :width 15%
# [[./textos/instituciones.org][file:img/0elConn.jpg]]
- [[./textos/instituciones.org][Calendario e instituciones de reelección]] (base de datos descargable, 20/5/2017)
# #+ATTR_HTML: style="float:right;"
# #+ATTR_HTML: :width 15%
# [[./textos/instituciones.org][file:img/gooReel.png]]

--------------------------------------
* Agradecimientos
Eric Magar agradece el generoso apoyo de la Asociación Mexicana de Cultura A.C. y del Sistema Nacional de Investigadores para la realización de este trabajo. Los errores y omisiones son mi entera responsabilidad. 

--------------------------------------



