#+TITLE: Valores encontrados
#+AUTHOR: Eric Magar
#+DATE:  <2017-08-29>
#+OPTIONS: toc:nil # don't place toc in default location
# # will change captions to Spanish, see https://lists.gnu.org/archive/html/emacs-orgmode/2010-03/msg00879.html
#+LANGUAGE: es 

# style sheet
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />

#+BEGIN_CENTER
por

*Ciro Murayama*[fn:1]
#+END_CENTER

#+OPTIONS: broken-links:mark

# #+LINK_UP: index.html
[[../index.html][Arriba/up]]


La Constitución Política abrió la puerta en 2014 a la reelección de representantes populares y mandatarios ---estos últimos sólo en el nivel de los ayuntamientos--- en México. En el nivel federal, la posibilidad de aspirar a ocupar un mismo cargo de forma ininterrumpida se acota a los legisladores, y serán los integrantes de la LXIV Legislatura del Congreso de la Unión, que se instalará el 1° de septiembre de 2018, los primeros que puedan buscar la reelección. En el terreno local, la oportunidad de volver a ser electo para regidor, alcalde y diputado se generalizará en las elecciones del próximo año, es decir, en los procesos electorales que comienzan en el último tramo de 2017. Ese mero hecho, junto con el barroquismo que caracteriza a la legislación electoral mexicana, hace oportuno y necesario discutir cómo se aterrizará la opción de que un ciudadano que ocupa un cargo electo aspire a ser nombrado para el mismo  nuevamente sin dejar pasar al menos un periodo electivo de por medio.

Para contribuir a esa deliberación me propongo problematizar cómo debe entenderse la reelección misma para, de ahí, perfilar algunas consideraciones acerca de cómo, sin reinventar el hilo negro y aprovechando disposiciones constitucionales vigentes, se puede dar vigencia a esta figura sin aún más abigarrado el diseño electoral de que disponemos.

La reforma de 2014 para permitir la elección consecutiva de ciudadanos elimina una restricción que era generalizada ---se mantiene para el titular del Ejecutivo federal y los gobernadores, así como para los alcaldes con mandatos superiores a los tres años--- y, de esa forma, amplía el derecho al voto pasivo, es decir, a ser votado. De esta manera, el principal sujeto de la reelección es el ciudadano que ha sido electo y busca serlo otra vez para el inmediato. De ahí que sea oportuno identificar, una vez que se amplió un derecho, qué responsabilidades conlleva ejercerlo. Ello conduce a definir las reglas de juego para quien se presente a la reelección.

Parto de la idea de que en los países donde existe la figura de la reelección, ésta se aplica para quienes ejercen un cargo de elección popular y cuya nueva aparición en la boleta electoral no pasa por la separación del cargo. El énfasis viene a cuento porque si se piensa que, digamos, un alcalde puede presentarse a la reelección pero a la vez ha de separarse de sus funciones, entonces no tendremos sino que aplicar los requisitos de elegibilidad que han prevalecido desde hace décadas, en el sentido de que los candidatos deben separarse de ciertos cargos públicos con determinada antelación al registro de su postulación, con la única diferencia de que esa disposición se aplicará también para el propio cargo que se quiera volver a buscar.

En otras palabras: hasta antes de la reforma un diputado que quería ser senador había de pedir licencia como diputado; ahora, un diputado que quisiera volver a ser diputado, igualmente debería pedir licencia como diputado. O un presidente municipal que haya querido ser gobernador o legislador, ha tenido que pedir licencia como regidor; ahora un presidente municipal que aspirara a ser reelecto como tal tendría que apartarse de su cargo para buscar sentarse en el mismo lugar de forma consecutiva. Esta última opción facilita la vida de la autoridad electoral (nadie en un cargo público haría campaña o incluso precampaña, lo que hace menos complicada la tarea de control y fiscalización) pero, en los hechos, desnaturaliza la propia idea de reelección tal como se aplica en buena parte del mundo democrático, sin mayores contratiempos ni complicaciones.

Si se miran otras experiencias nacionales, la constante en esta materia es que quienes tienen los cargos públicos culminen el periodo para el que fueron electos y puedan repetir si el voto popular los favorece ---el caso más emblemático puede ser el del presidente de los Estados Unidos de América tras concluir su primera administración. En sistemas parlamentarios, que son predominantemente en Europa, el titular del Ejecutivo surge de los legisladores sin que se limite en general el número de veces que éstos pueden postularse al Congreso y, por supuesto, sin que deban separarse del cargo para seguir participando en la vida política electoral. De esta manera la separación anticipada del cargo suele darse más por renuncia o por sanción, lo que implica que el individuo involucrado, a partir de ello, se retire de la vida política. Así, en el grueso de los países la separación anticipada de un cargo de elección es definitiva, es el adelanto del fin de la permanencia en un puesto, no una condición para regresar a él unos meses después. 

Si el camino por el que se optara al concretar la reelección en México fuese obligar al titular del cargo electo a separarse del mismo para poder buscarlo inmediatamente, no habría mayor discusión y este artículo podría terminar aquí. Bastaría con fijar fechas de separación del cargo antes de concluir el periodo de cada figura ---así ocurre incluso con la legislación de Nayarit al respecto. Pero como mi propósito no es zanjar discusiones ni adelantar conclusiones ---que deberían involucrar al Poder Legislativo con una reglamentación secundaria más afinada de la reelección y, ante una eventual omisión legislativa en la materia, a la autoridad electoral administrativa y al Tribunal Electoral---, continúo con la problematización. 

¿Qué razones nos deberían de llevar en México a apartarnos de lo que es normal en buena parte del mundo y obligar a quien quiera reelegirse a separarse del cargo? Quizá la preocupación tenga que ver con la equidad, con evitar ventajas ilegítimas para quien se presente a la reelección consecutiva. Si es así, lo que conviene es precisar las reglas para proteger la equidad ---un principio irrenunciable para tener contiendas electorales genuinas--- en vez de desnaturalizar la reelección y seguir contribuyendo al barroco electoral mexicano. 

Así que, un vez definido que el "incumbente" ---horrible aunque útil traducción del término inglés /incumbent/, esto es, la personas que ejerce un cargo de responsabilidad, en este caso, gracias al voto popular--- se postulará sin separarse del cargo, ¿qué conducta se le debe exigir para evitar que desde su posición obtenga una ventaja ilegítima frente al resto de candidatos que, obviamente, tiene como objetivo expreso desplazarlo del cargo? Me parece que esa definición de lo que no se debe hacer desde un cargo público para incidir en la ciudadanía o para afectar la equidad en la contienda electoral ya está diáfanamente redactada en la Constitución Política, en particular en los párrafos séptimo y octavo del artículo 134, que a la letra dicen: 

	Los servidores públicos de la Federación, las entidades federativas, los Municipios y las demarcaciones territoriales de la Ciudad de México, tienen en todo tiempo la obligación de aplicar con imparcialidad los recurso públicos que están bajo su responsabilidad, sin influir en la equidad de la competencia entre los partidos políticos. 

	La propaganda, bajo cualquier modalidad de comunicación social, que difundan como tales, los poderes públicos, los órganos autónomos, las dependencias y entidades de la administración pública y cualquier otro ente de los tres órdenes de gobierno, deberá tener carácter institucional y fines informativos, educativos o de orientación social. En ningún caso esta propaganda incluirá nombres , imágenes, voces o símboles que impliquen promoción personalizada de cualquier servidor público. 

Si bien el artículo 134 aún carece de reglamentación secundaria, su trazo no deja dudas de que el uso de los recursos públicos por los servidores públicos en ningún caso debe influir en la equidad de la competencia electoral. Un regidor, alcalde o legislador hoy está impedido constitucionalmente para gastar a favor de su partido, y con la reelección ese impedimento se extendería a favorecerse a sí mismo como contendiente. En una nuez: el dinero público debe usarse de manera imparcial, te busques reelegir o no, punto.

En lo que toca al párrafo octavo del artículo 134, también es diáfano al señalar que como servidor público nadie puede autopromocionarse en la propaganda institucional, ni con nombre, imagen, voz o símbolos alusivos al gobernante, al incumbente ---por cierto, palabra muy al uso en países latinoamericanos para referirse a quien va a una elección ocupando el cargo en disputa. Para decirlo en una línea: quien busque la reelección no podrá financiar su propaganda política ni sus gastos de campaña con recursos del municipio o de la Cámara legislativa donde sirva.

Lo anterior nos lleva entonces a delimitar entre las funciones del regidor, presidente municipal o legislador, y las del político en campaña, tal como ocurre en otras legislaciones. Por ejemplo, en Colombia la Ley 966 regula de forma específica la participación del presidente y del vicepresidente del país cuando son además, cadnidatos a reelegirse.  Así, durante el tiempo que duran las campañas (40 días) tienen determinadas limitaciones que pretenden abonar a la equidad en la contienda electoral.  Se regula la presencia en los medios, en especial las transmisiones presidenciales en Radio Televisión Nacional de Colombia, así como se imponen restricciones a la contratación pública del gobierno colombiano. Destaca que, cuando el presidente se haya inscrito como candidato a la elección presidencial, no podrán ser transmitidas por el Canal Institucional del Estado las reuniones con comunidades para promover la gestión del gobierno en la solución de los problemas que las aquejan ---con excepción de las reuniones relacionadas con seguridad nacional, soberanía, orden público o desastres naturales. Además, durante los cuatro meses anteriores a la fecha de votación en primera vuelta (y hasta la segunda vuelta, si fuera el caso), el presidente y el vicepresidente no pueden asistir a actos de inauguración de obras públicas; entregar personalmente recursos o bienes estatales; referirse a los demás candidatos o movimientos políticos en sus disertaciones o presentaciones públicas, como jefe de Estado o de gobierno; ni utilizar o incluir la imagen, símbolos o consignas de su campaña presidencial en la publicidad del gobierno. 

Además, en Colombia estos candidatos no pueden utilizar bienes del Estado en actividades de su campaña presidencial, siempre y cuando sean diferentes a los propios de sus funciones y a aquellos destinados de su seguridad personal. La ley es tan detallada, que especifica que el monto de la publicidad estatal no podrá aumentar durante la campaña presidencial. Asimismo, se suspende cualquier afectación a la nómina estatal durante este periodo y se prohíben las contrataciones directas por parte de todos los entes del Estado. 

Si bien en el caso mexicano la reelección no operará para el presidente de la República ---y qué bueno que así sea---, el marco de Colombia nos ofrece un buen ejemplo. De lo que se trata es de evitar que haya una ventaja ilegítima de quien está en el cargo. Cabe señalar que es inevitable que de cara a una campaña ciertos candidatos sean más conocidos que otros, que la ciudadanía tenga más referencias  del candidato A que del B o C, pero eso no necesariamente da lugar a una ventaja ilegítima. En el caso de la reelección, quienes han gobernado u ocupado un cargo legislativo pueden ser más conocidos, ellos pueden mostrar los logros de su trabajo como funcionarios públicos, pero también ser cuestionados más fácilmente por su desempeño.

El quid radica entonces en evitar ventajas ilegítimas y por eso ha de entenderse el abuso del puesto para ganar la siguiente elección, esto es, el uso de recursos públicos o la promoción con cargo a la propaganda oficial del mandatario o legislador que busca reelegirse. O dicho de otra forma, para que no haya ventaja ilegítima en la reelección ha de hacerse valer el artículo 134 constitucional que, valga la obviedad, ya está redactado y es vigente. Además, hay normas complementarias, como la prohibición de difundir campañas gubernamentales durantes las contiendas electorales.

Entonces, lo que corresponde es deslindar entre actividades de campaña y actividades de gobierno, así como limitar lo que puede hacer un gobernante que sea a la vez candidato. Más que llevarlo a la separación anticipada ---y quizá temporal--- del cargo, lo que hay que definir es que no pueda inaugurar obra pública o asistir a actos como gobernante que en realidad sean actos de proselitismo electoral.
Una ruta para explorar es que, desde el inicio de las precampañas, quien busque la reelección no puede realizar eventos masivos, acudir a actos de inauguración, y para todo lo que tenga que ver con actividades proselitistas, no pueda usar recursos públicos como vehículos, inmuebles, personal, equipos de comunicación, por ejemplo. Tampoco sería válido hacer coincidir la presentación y difusión de informes de labores ---por cierto, una figura a partir de la cual se han dado abusos para la promoción personalizada de servidores públicos--- con los periodos electorales.

Si se permitiera la reelección sin la obligación de separarse del cargo ---la Constitución no contempla ese extremo, por lo que jurídicamente es pertinente cuestionar si es viable imponer esa restricción para el ejercicio del voto pasivo---, sería necesario trascender de lo estipulado en distintas sentencias del Tribunal Electoral en el sentido de que los servidores públicos sólo pueden asistir a actos políticos en días inhábiles. 

Como se ve, ir a contiendas con posibilidad de reelección exige diferentes definiciones. El debate está abierto, sea bienvenido.

[fn:1] Consejero Electoral del Instituto Nacional Electoral. Este artículo fue publicado en la revista /Voz y voto/, número 292, junio 2017. El autor ha dado su autorización para reproducirlo aquí.

