#+TITLE: ¿Cómo reelegirse en la CDMX?
#+AUTHOR: Eric Magar
#+DATE:  <2017-11-28>
#+OPTIONS: toc:nil # don't place toc in default location
# # will change captions to Spanish, see https://lists.gnu.org/archive/html/emacs-orgmode/2010-03/msg00879.html
#+LANGUAGE: es 

# style sheet
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />

#+BEGIN_CENTER
por

*Yuri Beltrán Miranda*[fn:1]
#+END_CENTER

#+OPTIONS: broken-links:mark

# #+LINK_UP: index.html
[[../index.html][Arriba/up]]

A partir de este año la capital de la República tiene Constitución propia, la norma fundamental más actual del país. Pero más allá de su reciente expedición, la Constitución de la Ciudad de México cobra vigencia por el interés que sus redactores pusieron para conjugar en ella principios democráticos de avanzada con una organización política más eficiente. No sólo se revisaron las constituciones de otras entidades federativas, también se examinaron tratados internacionales, normas de grandes ciudades y una enorme cantidad de propuestas formuladas por ciudadanos y organizaciones. 

Toda vez que la reelección es uno de los desafíos más inmediatos que enfrenta la vida política del país, resulta interesante conocer cuál fue el tratamiento que el Constituyente local le dio y qué expectativas se tienen sobre su concreción en la nueva legislación electoral.[fn:2] 

* Antecedente

Como es sabido, la reforma constitucional de 2014 transformó el modelo electoral mexicano. Uno de los cambios que más llamaron la atención fue la reincorporación de la reelección de legisladores y presidentes municipales, que había sido desterrada de la Carta Magna en 1933.

Un año antes, en 2013, la Comisión Europea para la Democracia a través del Derecho revisó la normativa electoral mexicana a la luz de estándares democráticos internacionales. Sugirió revisar la prohibición de reelegirse, ya que la limitación del mandato podía afectar el principio de representación y la práctica democrática actual. A decir de la Comisión de Venecia, mantener la prohibición podía generar un Congreso inexperto, lo que a su vez se traduciría en desbalances a favor del Poder Ejecutivo.[fn:3] 

Así, el nuevo texto constitucional federal establece para los senadores hasta dos períodos consecutivos (12 años), mientras que los diputados podrán reelegirse hasta por cuatro períodos (12 años también). Si bien fijó reglas para la elección partidista, nada dijo sobre el caso de quienes hayan accedido al cargo de una candidatura independiente. 

Para los cargos de elección de naturaleza local y municipal se determinó que los legisladores estatales puedan reelegirse hasta por cuatro períodos consecutivos (los mismos 12 años). Los presidentes municipales, regidores y síndicos podrán hacerlo por un periodo adicional, siempre y cuando el tiempo del mandato de los ayuntamientos no sea superior a tres años.

La reelección no operó de forma inmediata. No fue aplicable a los legisladores que hubieran protestado el cargo en la Legislatura 2012-2015 y se precisó que en los cargos municipales no sería aplicable a quienes hubieran tomado protesta en 2014. 

* Armonización en entidades federativas

A partir de los parámetros establecidos por el Poder Reformador de la Constitución federal, las entidades federativas adecuaron su legislación electoral. Aquí algunos resultados.[fn:4] 

/Diputados/. 23 entidades federativas replicaron el modelo federal, que permite la reelección en cuatro periodos consecutivos. Ocho entidades la establecieron por dos periodos y en Morelos se decidió que fuera por tres periodos.

/Ayuntamientos/. 30 entidades optaron por seguir el modelo federal, que permite sólo dos periodos para gobernar. En Hidalgo y Veracruz no se legisló la reelección de ayuntamientos, puesto que el tiempo que duran en el cargo es cuatro años y está condición es la limitante establecida en el texto federal.[fn:5]

El Estatuto de Gobierno del Distrito Federal consideró que los diputados a la Asamblea Legislativa podrían ser electos hasta por cuatro periodos consecutivos y que los jefes delegacionales podrían serlo hasta por dos periodos consecutivos, de tres años cada uno. 

La posibilidad de reelección para quienes hayan accedido al cargo como independientes fue resuelta en la legislación de algunas entidades federativas. El modelo adoptado por Baja California, Coahuila, Chihuahua, Jalisco, Querétaro, Sonora, Tabasco y Tamaulipas, en forma general, establece que quienes hayan sido electos como independientes sólo podrán postularse para la reelección con la misma calidad.[fn:6] 

Es interesante la distinción que hacen algunas legislaciones sobre el principio por el que se postulan quienes consideran reelegirse. Aguascalientes, Coahuila y Zacatecas permiten que cualquier diputado o funcionario municipal, sin importar por el principio por el que hayan llegado al cargo, mayoría relativa o representación proporcional, sean postulados bajo cualquiera de las dos modalidades. En cambio Guerrero precisó que los electos por mayoría relativa podrán postularse bajo cualquier principio, no así los de representación proporcional, quienes deberán agotar la misma vía. Por su parte, Puebla precisa que los de mayoría relativa sólo podrán proponerse para el mismo distrito por el que hayan llegado y los de representación proporcional, por cualquiera de las vías.[fn:7]

* La Constitución de la Ciudad de México 

En enero de 2016 se modificó la Constitución del país y se dio inicio a la reforma del Distrito Federal y la creación a la Ciudad de México. Toda vez que las disposiciones electorales de la nueva Carta Magna local entrarían en vigor para la elección de 2018, el Constituyente Federal explícitamente prohibió a los actuales delegados y diputados de la Asamblea Legislativa participar como candidatos a alcaldes o diputados en la elección de ese año (artículo tercero y cuatro transitorios). 

El 5 de febrero de 2017 se publicó la Constitución Política de la Ciudad, cuyo contenido electoral está vigente desde el día siguiente al de su publicación.[fn:8] La Carta señala que los diputados al Congreso de la Ciudad de México podrán ser reelectos para un solo periodo consecutivo y reitera que la postulación deberá ser realizada por el mismo partido o por cualquiera de los partidos integrantes de la coalición que los haya postulado, salvo renuncia o pérdida de su militancia antes de la mitad del mandato.

Además regula la reelección para los diputados que hayan llegado por la vía independiente. Establece que quienes accedieron al Congreso por una candidatura sin partido, deberán conservar esta calidad para pode ser reelectos. 

Para las alcaldías, señala que las alcaldesas y los alcaldes y concejales podrán ser electos consecutivamente para el mismo cargo hasta por un periodo adicional;[fn:9] sin embargo, no podrán ser electos para el periodo inmediato posterior en una alcaldía distinta a aquella en la que desempeñado el cargo. 

Como es sabido, el Alto Tribunal deberá resolver acciones de inconstitucionalidad y controversias constitucionales formuladas por quienes consideran que la Constitución de la Ciudad de México viola preceptos de la Carta Magna del país.[fn:10] 

En la acción interpuesta por la Procuraduría General de la República se planteó que existía una transgresión de los derechos humanos de carácter político de los habitantes de la Ciudad de México, al limitar la reelección de los diputados a un periodo consecutivo. Se alega que la Asamblea Constituyente no tenía la facultad para decidir el número de periodos, sino que reconoce un derecho político para las y los ciudadanos de la Ciudad de México, de ser electos como diputados a la Legislatura local, en forma consecutiva, hasta por cuatro periodos. Al ser consultada sobre el particular, la Sala Superior del TEPJF recordó (SUP-OP-002/2017) que la SCJN ya ha resuelto (acciones de inconstitucionalidad 126/2015 y 127/2015)[fn:11] que las entidades federativas “tienen libertad de configuración legislativa para regular el régimen de la elección consecutiva de los diputados, incluyendo el número de periodos adicionales, siempre y cuando las normas cumplan , como cualquier otra, con criterios de proporcionalidad y razonabilidad”, dado que “el texto constitucional federal sólo impuso un tope de ocasiones, ya que utilizó la locución “hasta” y no un número de veces determinado”.

* ¿Qué esperar de la legislación electoral de la Ciudad?

Resulta prematuro especular cómo quedará nuestra legislación electoral. Están por definirse intensos debates sobre las reglas específicas que guiarán la posibilidad de que los electos puedan competir nuevamente por el mismo cargo. 

No obstante, las iniciativas presentadas dan alguna luz sobre los elementos que los diputados tendrán a la vista al regular la reelección en la Ciudad de México. Cuando menos seis propuestas hacen importantes aportaciones al respecto.[fn:12] A continuación se describen las más significativas. 

/Renuncia al cargo/. No se encontraron iniciativas que indiquen que quienes pretendan la reelección deben renunciar al cargo al que hayan sido electos originalmente. 

/Requisitos/. Algunas iniciativas consideran solicitar a quien quiera ser reelecto una carta en la que especifique los periodos para los que ha sido electo en ese cargo. 

/Militancia partidista/. Quienes en la elección original hayan sido postulados por un partido, sólo podrán buscar la reelección postulados por el mismo partido, a menos que hayan renunciado en la primera mitad de su mandato. 

/Candidaturas independientes/. La gran mayoría de la las iniciativas contiene reglas para que los independientes puedan ser reelectos. Mientras que algunos exigen que se mantengan sin afiliación a partido político alguno, otras abren la posibilidad de que se afilien, siempre que sea en la primera mitad de su mandato. 

/Alcaldías/. En general se reconoce la posibilidad de que alcaldes y concejales se postulen para un periodo adicional, aunque no en una demarcación territorial distinta a aquella en que hayan sido electos originalmente. 

/Registro/. Un partido sugiere que se registren por separado los titulares que estén buscando la Reelección. 

/Vida interna de partidos/. Existe una propuesta en el sentido de que, quienes quieran reelegirse, necesariamente hayan rendido su informe de labores. En dicho ejercicio deberán haberse abstenido de manifestar su intención de reelegirse. 

/Uso de recursos públicos/. La iniciativa del PAN incluye normas para evitar el uso de recursos públicos en las campañas de los ya electos. Entre otras, la prohibición de que los colaboradores del titular que pretenda reelegirse participen en precampañas (salvo en horario no laboral); la restricción para los titulares que quieran reelegirse, de utilizar los recursos públicos inherentes a su cargo (vehículo, instalaciones, etc.) para actos de precampaña o campaña; y la idea de que se descuenten las ausencias a las sesiones a quienes estén compitiendo por la reelección. 

* Retos Legislativos

/Paridad de género/. Existen tensiones entre la posibilidad de reelección y el principio de paridad. Se vuelven todavía más significativas en el caso de la Ciudad de México, toda vez que la Constitución prevé la “Integración paritaria” del Congreso.

/Vida interna de los partidos políticos/. El problema de la paridad y el de la reelección demanda la discusión sobre lo que pueden hacer los partidos políticos para garantizar la correcta aplicación de ambos principios. 

/Principio por el que se postulan/. Sería útil que la legislación electoral especificara si será posible cambiar el principio por el que un candidato se postule, o si necesariamente deba competir por mayoría o por representación, según lo haya hecho originalmente. 

/Alcaldías/. La Constitución local abre la necesidad de que se reviste la geografía de las alcaldías existentes una vez que concluya el proceso electoral de 2018. Sería necesario que la legislación electoral previera cómo los nuevos trazos afectarían las posibilidades de ser reelectos. 

La gran apuesta de la reforma de 2014apenas está por comenzar. La legislación impone grandes desafíos a la administración electoral. Estos retos se pueden afrontar mejor si la regulación es clara y se dan los pasos administrativos con oportunidad. 

En la medida en que las autoridades, partidos y ciudadanos adoptemos con responsabilidad las reglas de la reelección, menos tropiezos habrá.     


[fn:1] Consejero electoral del Instituto Electoral del Distrito Federal. Este artículo fue publicado en la revista /Voz y voto/, número 292, junio 2017. El autor ha dado su autorización para reproducirlo aquí.

[fn:2] Al momento de redacción de este artículo, la Asamblea Legislativa del Distrito Federal está discutiendo la legislación electoral que operará en la elección de 2018.

